#The ip_address of the lecroy
ip: 192.168.1.12

#runName is the name in ~/Desktop/ssrl/ that all data will be stored
runName: "potatoe" 

#Time is in units of minutes
time:
 motor: 1000000 #How long do we wait for the motor tigger 
 beam: 30 #How long is a beam run
 unit: "sec" #Either min or sec

#Threshold is in V
#For auxillary trigger use "AUX" else use "C1","C2","C3","C4" in channel
trigger:
 motor:
  channel: "AUX" 
  threshold: 0.5
 beam:
  channel: "C1"
  threshold: 0.004
